return {
  -- {
  -- 'm4xshen/hardtime.nvim', -- Helps establish good command use and helps quit bad habits
  -- }
  -- {
  -- 	-- Runs unit tests for various languages.
  -- 	-- See https://github.com/nvim-neotest/neotest.
  -- 	-- This does not work right now.
  -- 	"nvim-neotest/neotest",
  -- 	dependencies = {
  -- 		"nvim-neotest/nvim-nio",
  -- 		"nvim-lua/plenary.nvim",
  -- 		"antoinemadec/FixCursorHold.nvim",
  -- 		"nvim-treesitter/nvim-treesitter",
  -- 		"fredrikaverpil/neotest-golang",
  -- 	},
  -- 	config = function()
  -- 		vim.keymap.set("n", "<leader>th", function()
  -- 			require("neotest").run.run(vim.fn.expand("%"))
  -- 		end, { desc = "Neo[t]est [h]ere" })
  -- 		vim.keymap.set("n", "<leader>tso", function()
  -- 			require("neotest").summary.open()
  -- 		end, { desc = "Neo[t]est [s]ummary [o]pen" })
  -- 		vim.keymap.set("n", "<leader>tsc", function()
  -- 			require("neotest").summary.close()
  -- 		end, { desc = "Neo[t]est [s]ummary [c]lose" })
  --
  -- 		require("neotest").setup({
  -- 			adapters = {
  -- 				require("neotest-golang")({}),
  -- 			},
  -- 		})
  -- 	end,
  -- }
  -- {
  -- -- Not sure if this works.
  -- "antosha417/nvim-lsp-file-operations",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   -- Uncomment whichever supported plugin(s) you use
  --   "nvim-tree/nvim-tree.lua",
  --   -- "nvim-neo-tree/neo-tree.nvim",
  --   -- "simonmclean/triptych.nvim"
  -- },
  -- opts = {
  --   -- used to see debug logs in file `vim.fn.stdpath("cache") .. lsp-file-operations.log`
  --   debug = false,
  --   -- select which file operations to enable
  --   operations = {
  --     willRenameFiles = true,
  --     didRenameFiles = true,
  --     willCreateFiles = true,
  --     didCreateFiles = true,
  --     willDeleteFiles = true,
  --     didDeleteFiles = true,
  --   },
  --   -- how long to wait (in milliseconds) for file rename information before cancelling
  --   timeout_ms = 10000,
  -- },
  -- config = function(_, opts) require("lsp-file-operations").setup(opts) end,
  -- }
}
